import { useEffect, useState } from "react";
import { Bot, Bus, Check, ChevronLeft, ChevronRight, Clock3, MapPin, Route, SlidersHorizontal, Sparkles, UsersRound } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Label } from "@/components/ui/label";
import { Slider } from "@/components/ui/slider";
import { Switch } from "@/components/ui/switch";
import { drivers, vehicles } from "@/lib/mock-data";
import { cn } from "@/lib/utils";
import { toast } from "sonner";

const progressSteps = ["Analyse de 426 adresses", "Regroupement géographique", "Analyse des véhicules disponibles", "Vérification des capacités", "Analyse des chauffeurs", "Génération des itinéraires", "Optimisation", "Vérification des contraintes", "Finalisation"];

export function AiPage() {
  const [step, setStep] = useState(1);
  const [generating, setGenerating] = useState(false);
  const [progress, setProgress] = useState(0);
  const [result, setResult] = useState(false);
  useEffect(() => { if (!generating) return; const timer = window.setInterval(() => setProgress((p) => { if (p >= 100) { window.clearInterval(timer); setGenerating(false); setResult(true); return 100; } return p + 4; }), 110); return () => window.clearInterval(timer); }, [generating]);
  const generate = () => { setProgress(0); setGenerating(true); };
  return <AppShell title="Agent IA Transport" eyebrow="Agent IA – Optimisation">
    <section className="relative overflow-hidden rounded-lg bg-ai-panel p-6 text-ai-foreground shadow-ai md:p-8"><div className="absolute right-0 top-0 size-64 translate-x-1/3 -translate-y-1/3 rounded-full border border-ai-foreground/10" /><div className="absolute right-12 top-12 size-40 rounded-full border border-ai-foreground/10" /><div className="relative flex flex-col justify-between gap-6 md:flex-row md:items-center"><div className="flex gap-4"><div className="grid size-14 shrink-0 place-items-center rounded-md bg-ai-foreground/10"><Bot className="size-7" /></div><div><p className="mb-2 flex items-center gap-2 text-xs font-bold uppercase text-accent"><Sparkles className="size-3.5" />Assistant intelligent</p><h2 className="font-display text-2xl font-bold md:text-3xl">Optimisez automatiquement vos circuits</h2><p className="mt-2 max-w-2xl text-sm text-ai-foreground/70">Répartissez les élèves, véhicules et chauffeurs selon vos contraintes opérationnelles.</p></div></div><div className="flex shrink-0 gap-4 text-center"><span><b className="block text-xl">426</b><small className="text-ai-foreground/60">élèves</small></span><i className="w-px bg-ai-foreground/20"/><span><b className="block text-xl">11</b><small className="text-ai-foreground/60">bus prêts</small></span></div></div></section>
    {!result ? <section className="mt-6 rounded-lg border bg-card shadow-sm">
      <div className="grid border-b md:grid-cols-4">{["Élèves", "Véhicules", "Chauffeurs", "Paramètres"].map((label,i) => <button key={label} onClick={() => !generating && setStep(i+1)} className={cn("relative flex items-center justify-center gap-2 px-4 py-4 text-sm font-semibold transition-colors", step === i+1 ? "text-primary" : "text-muted-foreground")}><span className={cn("grid size-6 place-items-center rounded-full text-xs", step > i+1 ? "bg-success text-success-foreground" : step === i+1 ? "bg-primary text-primary-foreground" : "bg-muted")}>{step > i+1 ? <Check className="size-3.5" /> : i+1}</span>{label}{step === i+1 && <span className="absolute bottom-0 left-0 h-0.5 w-full bg-primary" />}</button>)}</div>
      <div className="min-h-[390px] p-6 md:p-8">{generating ? <div className="mx-auto max-w-2xl py-12 text-center"><div className="mx-auto mb-6 grid size-20 place-items-center rounded-full bg-secondary/10 text-secondary"><Bot className="size-9 animate-pulse" /></div><h3 className="text-xl font-bold">Optimisation en cours…</h3><p className="mt-2 text-muted-foreground">{progressSteps[Math.min(8, Math.floor(progress / 12))]}</p><Progress value={progress} className="mt-7 h-2" /><p className="mt-3 text-sm font-semibold text-secondary">{progress}%</p></div> : <WizardStep step={step} />}</div>
      {!generating && <div className="flex items-center justify-between border-t p-5"><Button variant="outline" disabled={step === 1} onClick={() => setStep(step-1)}><ChevronLeft />Précédent</Button>{step < 4 ? <Button onClick={() => setStep(step+1)}>Continuer<ChevronRight /></Button> : <Button size="lg" onClick={generate} className="shadow-lg"><Sparkles />Générer les circuits avec l’IA</Button>}</div>}
    </section> : <AiResults onRestart={() => { setResult(false); setStep(4); }} />}
  </AppShell>;
}

function WizardStep({ step }: { step: number }) {
  if (step === 1) return <div><Header icon={UsersRound} title="Quels élèves souhaitez-vous inclure ?" detail="426 élèves ont actuellement besoin du transport scolaire." /><RadioGroup defaultValue="all" className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[["all","Tous les élèves","426 élèves"],["level","Par niveau","Maternelle à Lycée"],["class","Par classe","Sélection précise"],["zone","Par zone","11 quartiers"],["custom","Sélection personnalisée","Choisir les élèves"]].map(([v,l,d]) => <Label key={v} htmlFor={v} className="flex cursor-pointer gap-3 rounded-md border p-4 hover:border-secondary"><RadioGroupItem value={v} id={v}/><span><b className="block">{l}</b><small className="text-muted-foreground">{d}</small></span></Label>)}</RadioGroup></div>;
  if (step === 2) return <div><Header icon={Bus} title="Sélectionnez les véhicules disponibles" detail="11 véhicules disponibles sur 14" /><div className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{vehicles.map(v => <label key={v.id} className={cn("rounded-md border p-4", v.status === "Maintenance" || v.status === "Indisponible" ? "cursor-not-allowed bg-muted opacity-50" : "cursor-pointer hover:border-secondary")}><input type="checkbox" defaultChecked={v.status !== "Maintenance" && v.status !== "Indisponible"} disabled={v.status === "Maintenance" || v.status === "Indisponible"} className="mb-4 accent-secondary" /><b className="block">Bus {v.id}</b><span className="text-sm text-muted-foreground">{v.brand} {v.model}</span><span className="mt-3 block text-xs">{v.capacity} places · {v.status}</span></label>)}</div></div>;
  if (step === 3) return <div><Header icon={UsersRound} title="Sélectionnez les chauffeurs" detail="12 chauffeurs disponibles aujourd’hui" /><div className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{drivers.slice(0,12).map((d,i) => <label key={d.id} className="flex cursor-pointer items-center gap-3 rounded-md border p-4 hover:border-secondary"><input type="checkbox" defaultChecked className="accent-secondary" /><span className="grid size-10 place-items-center rounded-full bg-secondary/10 font-bold text-secondary">{d.name.split(" ").map(x=>x.charAt(0)).join("")}</span><span><b className="block text-sm">{d.name}</b><small className="text-muted-foreground">{i < 10 ? d.vehicle : "Véhicule flexible"} · {d.hours}</small></span></label>)}</div></div>;
  return <div><Header icon={SlidersHorizontal} title="Paramètres d’optimisation" detail="Ajustez les priorités et les contraintes du calcul." /><div className="mt-7 grid gap-7 lg:grid-cols-2"><div><Label>Objectif prioritaire</Label><RadioGroup defaultValue="balanced" className="mt-3 space-y-2">{["Équilibre recommandé", "Minimiser la distance globale", "Minimiser le temps de trajet", "Équilibrer les capacités", "Réduire le nombre de bus"].map((x,i)=><Label key={x} className="flex cursor-pointer items-center gap-3 rounded-md border p-3"><RadioGroupItem value={i===0?"balanced":String(i)} />{x}</Label>)}</RadioGroup></div><div className="space-y-5"><div><div className="mb-3 flex justify-between text-sm"><Label>Durée maximale souhaitée</Label><b>45 min</b></div><Slider defaultValue={[45]} min={20} max={75} step={5}/></div>{["Respecter strictement la capacité", "Conserver les fratries ensemble", "Conserver les affectations existantes"].map((x,i)=><div key={x} className="flex items-center justify-between rounded-md border p-4"><span className="text-sm font-medium">{x}</span><Switch defaultChecked={i<2}/></div>)}</div></div></div>;
}

function Header({ icon: Icon, title, detail }: { icon: typeof Bus; title:string; detail:string }) { return <div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-md bg-secondary/10 text-secondary"><Icon /></div><div><h3 className="text-lg font-bold">{title}</h3><p className="text-sm text-muted-foreground">{detail}</p></div></div>; }

function AiResults({ onRestart }: { onRestart: () => void }) {
  const results = [["426","élèves analysés"],["11","bus disponibles"],["10","bus recommandés"],["10","circuits générés"],["12","chauffeurs disponibles"],["88 %","capacité utilisée"]];
  return <div className="mt-6 space-y-6 animate-fade-in"><div className="rounded-lg border border-success/30 bg-success-soft p-5"><div className="flex items-center gap-3 text-success"><span className="grid size-9 place-items-center rounded-full bg-success text-success-foreground"><Check /></span><div><h3 className="font-bold">Optimisation terminée</h3><p className="text-sm">Une proposition équilibrée a été générée avec succès.</p></div></div></div><div className="grid grid-cols-2 gap-3 lg:grid-cols-6">{results.map(([v,l])=><div key={l} className="rounded-lg border bg-card p-4 text-center shadow-sm"><b className="block text-2xl">{v}</b><span className="text-xs text-muted-foreground">{l}</span></div>)}</div><div className="grid gap-6 xl:grid-cols-[1.4fr_1fr]"><TangerMap /><div className="space-y-4">{[["C-01","Ziaten / Route de Rabat","B-03",42,45,93],["C-02","Mesnana / Boubana","B-06",38,45,84],["C-03","Iberia / Centre-ville","B-01",29,35,83]].map(([id,name,bus,count,cap,pct])=><article key={String(id)} className="rounded-lg border bg-card p-5 shadow-sm"><div className="flex justify-between"><div><b>{id} — {name}</b><p className="mt-1 text-xs text-muted-foreground">{bus} · Ahmed Benali · 8 arrêts</p></div><b className="text-secondary">{pct}%</b></div><Progress value={Number(pct)} className="mt-4 h-1.5"/><p className="mt-3 text-xs text-muted-foreground">Pourquoi cette proposition ? Les élèves sont regroupés par proximité; ce bus offre la capacité adaptée au créneau.</p></article>)}</div></div><div className="grid gap-4 md:grid-cols-2"><div className="rounded-lg border bg-card p-5"><p className="text-sm text-muted-foreground">Organisation actuelle</p><div className="mt-3 flex justify-between"><b>11 circuits · 11 bus</b><b>76 %</b></div></div><div className="rounded-lg border border-secondary/30 bg-secondary/5 p-5"><p className="text-sm text-secondary">Optimisation IA</p><div className="mt-3 flex justify-between"><b>10 circuits · 10 bus</b><b className="text-success">88 %</b></div></div></div><div className="flex flex-wrap gap-2"><Button onClick={()=>toast.success("Proposition validée")}>Valider cette proposition</Button><Button variant="outline" onClick={()=>toast("Mode de modification manuelle activé")}>Modifier manuellement</Button><Button variant="outline" onClick={onRestart}>Modifier les contraintes</Button><Button variant="ghost" onClick={()=>toast.success("Export préparé")}>Exporter</Button></div></div>;
}

function TangerMap() { return <div className="relative min-h-[480px] overflow-hidden rounded-lg border bg-map"><div className="absolute left-5 top-5 z-10 rounded-md bg-card/95 p-3 shadow"><p className="text-xs font-bold uppercase">Carte simulée · Tanger</p><div className="mt-2 flex gap-3 text-xs"><span className="text-primary">● C-01</span><span className="text-secondary">● C-02</span><span className="text-warning">● C-03</span></div></div><svg viewBox="0 0 700 480" className="absolute inset-0 size-full"><path d="M0 100 C110 120 170 70 260 95 S460 120 700 55 V0 H0Z" fill="var(--map-water)"/><g stroke="var(--map-road)" strokeWidth="10" fill="none" opacity=".9"><path d="M-20 400 Q180 250 380 310 T730 190"/><path d="M100 500 Q180 290 330 200 T640 80"/><path d="M40 220 Q230 180 420 230 T700 350"/></g><g fill="none" strokeLinecap="round" strokeWidth="5"><path d="M90 370 Q180 300 280 320 T520 180" stroke="var(--primary)"/><path d="M150 420 Q220 280 350 260 T590 110" stroke="var(--secondary)"/><path d="M80 230 Q260 200 400 250 T620 340" stroke="var(--warning)"/></g>{[[90,370],[180,315],[280,320],[410,275],[520,180],[150,420],[220,300],[350,260],[470,190],[590,110],[80,230],[220,205],[400,250],[520,290],[620,340]].map(([x,y],i)=><circle key={i} cx={x} cy={y} r="7" fill={i<5?"var(--primary)":i<10?"var(--secondary)":"var(--warning)"} stroke="var(--card)" strokeWidth="3"/>)}<circle cx="350" cy="260" r="15" fill="var(--foreground)" stroke="var(--card)" strokeWidth="5"/></svg><div className="absolute bottom-5 right-5 flex flex-col gap-1"><Button variant="outline" size="icon">+</Button><Button variant="outline" size="icon">−</Button></div></div>; }