import { AlertTriangle, ArrowDownRight, ArrowUpRight, Bus, Clock3, GraduationCap, Route, ShieldCheck, UsersRound, Wrench } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { circuits } from "@/lib/mock-data";
import { StatusBadge } from "@/components/status-badge";

const kpis = [
  ["Élèves transportés", "426", "+12 ce mois", GraduationCap, "positive"],
  ["Véhicules", "14", "11 disponibles", Bus, "neutral"],
  ["Chauffeurs disponibles", "12", "sur 15", UsersRound, "neutral"],
  ["Circuits actifs", "10", "Tous planifiés", Route, "positive"],
  ["En maintenance", "2", "B-03 · B-09", Wrench, "neutral"],
  ["Incidents ouverts", "3", "+2 cette semaine", AlertTriangle, "negative"],
] as const;

export function DashboardPage() {
  return <AppShell title="Bonjour Nadia," eyebrow="Tableau de bord">
    <p className="-mt-5 mb-7 text-muted-foreground">Voici l’activité du transport scolaire aujourd’hui, mardi 29 septembre.</p>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{kpis.map(([label, value, note, Icon, tone]) => <article key={label} className="group relative overflow-hidden rounded-lg border bg-card p-5 shadow-sm transition-all hover:-translate-y-0.5 hover:shadow-md"><div className="absolute right-0 top-0 h-1 w-16 bg-primary group-hover:w-full transition-all" /><div className="flex justify-between"><div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div><div className="grid size-11 place-items-center rounded-full bg-secondary/10 text-secondary"><Icon /></div></div><p className={`mt-4 flex items-center gap-1 text-xs font-semibold ${tone === "negative" ? "text-destructive" : tone === "positive" ? "text-success" : "text-muted-foreground"}`}>{tone === "negative" ? <ArrowUpRight className="size-3" /> : tone === "positive" ? <ArrowUpRight className="size-3" /> : <ArrowDownRight className="size-3" />}{note}</p></article>)}</div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.55fr_1fr]">
      <section className="overflow-hidden rounded-lg border bg-card shadow-sm"><div className="flex items-center justify-between border-b p-5"><div><h2 className="text-lg font-bold">Transport aujourd’hui</h2><p className="text-sm text-muted-foreground">Départs du matin en cours</p></div><span className="rounded-full bg-success-soft px-3 py-1 text-xs font-semibold text-success">8 / 10 terminés</span></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead className="bg-table-header text-left text-xs uppercase text-muted-foreground"><tr>{["Circuit", "Élèves", "Bus", "Chauffeur", "Horaire", "Statut"].map(x => <th key={x} className="px-5 py-3">{x}</th>)}</tr></thead><tbody>{circuits.slice(0,5).map(c => <tr key={c.id} className="border-t hover:bg-muted/40"><td className="px-5 py-4"><b>{c.id}</b><span className="block text-xs text-muted-foreground">{c.name}</span></td><td className="px-5">{c.students}</td><td className="px-5 font-medium">{c.vehicle}</td><td className="px-5">{c.driver}</td><td className="px-5">{c.time}</td><td className="px-5"><StatusBadge>{c.id === "C-05" ? "En route" : "Terminé"}</StatusBadge></td></tr>)}</tbody></table></div></section>
      <div className="space-y-6"><section className="rounded-lg border bg-card p-5 shadow-sm"><h2 className="text-lg font-bold">Disponibilité flotte</h2><div className="mt-5 flex items-center gap-7"><div className="relative grid size-36 place-items-center rounded-full bg-[conic-gradient(var(--secondary)_0_78.5%,var(--warning)_78.5%_92.5%,var(--destructive)_92.5%)]"><div className="grid size-24 place-items-center rounded-full bg-card text-center"><div><b className="block text-2xl">14</b><span className="text-xs text-muted-foreground">véhicules</span></div></div></div><div className="space-y-3 text-sm"><p><i className="mr-2 inline-block size-2 rounded-full bg-secondary" />11 disponibles</p><p><i className="mr-2 inline-block size-2 rounded-full bg-warning" />2 maintenance</p><p><i className="mr-2 inline-block size-2 rounded-full bg-destructive" />1 incident</p></div></div></section><section className="rounded-lg border bg-card p-5 shadow-sm"><h2 className="flex items-center gap-2 text-lg font-bold"><AlertTriangle className="size-5 text-primary" />Alertes</h2><div className="mt-3 divide-y">{["Bus B-07 indisponible", "Maintenance B-03 dans 4 jours", "Chauffeur indisponible mercredi", "5 élèves non affectés à un circuit"].map((x,i) => <div key={x} className="flex items-center gap-3 py-3 text-sm"><span className={`size-2 rounded-full ${i === 0 ? "bg-destructive" : "bg-warning"}`} />{x}</div>)}</div></section></div>
    </div>
    <section className="mt-6 rounded-lg border bg-card p-5 shadow-sm"><div className="mb-5 flex items-center gap-2"><Clock3 className="size-5 text-secondary" /><h2 className="text-lg font-bold">Planning du jour</h2></div><div className="grid gap-3 md:grid-cols-4">{[["06:45", "Départs matin", "10 circuits"], ["08:30", "Contrôle flotte", "Responsable parc"], ["12:10", "Navettes midi", "3 circuits"], ["15:45", "Départs soir", "10 circuits"]].map(([t,l,d]) => <div key={t} className="border-l-2 border-secondary pl-4"><b className="text-secondary">{t}</b><p className="mt-1 font-semibold">{l}</p><p className="text-xs text-muted-foreground">{d}</p></div>)}</div></section>
  </AppShell>;
}