import { useState } from "react";
import { Bus, Grid2X2, List, Plus } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { DataTable, statusCell } from "@/components/data-table";
import { ImportDialog, StudentDialog } from "@/components/dialogs";
import { StatusBadge } from "@/components/status-badge";
import { Button } from "@/components/ui/button";
import { circuits, drivers, students, vehicles } from "@/lib/mock-data";
import { toast } from "sonner";

export function StudentsPage() { return <AppShell title="Élèves"><PageIntro text="Gérez les élèves transportés, leurs affectations et points de ramassage."><ImportDialog /><StudentDialog trigger={<Button><Plus />Ajouter un élève</Button>} /></PageIntro><DataTable data={students} placeholder="Nom, matricule, quartier…" columns={[{key:"matricule",label:"Matricule"},{key:"name",label:"Nom complet"},{key:"level",label:"Niveau"},{key:"classroom",label:"Classe"},{key:"district",label:"Quartier"},{key:"circuit",label:"Circuit"},{key:"pickup",label:"Point de ramassage"},{key:"status",label:"Statut",render:statusCell("status")}]}/></AppShell>; }

export function VehiclesPage() {
  const [view, setView] = useState<"grid"|"table">("grid");
  return <AppShell title="Véhicules"><PageIntro text="Suivez la disponibilité et les prochaines échéances des 14 véhicules."><div className="flex rounded-md border p-1"><Button variant={view === "grid" ? "secondary" : "ghost"} size="icon" onClick={() => setView("grid")}><Grid2X2 /></Button><Button variant={view === "table" ? "secondary" : "ghost"} size="icon" onClick={() => setView("table")}><List /></Button></div><Button onClick={() => toast.success("Nouveau véhicule prêt à être renseigné")}><Plus />Ajouter</Button></PageIntro>{view === "grid" ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{vehicles.map(v => <article key={v.id} className="rounded-lg border bg-card p-5 shadow-sm transition-all hover:-translate-y-0.5 hover:shadow-md"><div className="flex justify-between"><div className="grid size-11 place-items-center rounded-md bg-secondary/10 text-secondary"><Bus /></div><StatusBadge>{v.status}</StatusBadge></div><h2 className="mt-5 text-xl font-bold">Bus {v.id}</h2><p className="text-sm text-muted-foreground">{v.brand} {v.model} · {v.capacity} places</p><div className="mt-5 grid grid-cols-2 gap-3 border-t pt-4 text-sm"><span><small className="block text-muted-foreground">Immatriculation</small>{v.plate}</span><span><small className="block text-muted-foreground">Circuit</small>{v.circuit}</span><span className="col-span-2"><small className="block text-muted-foreground">Prochain entretien</small>{v.maintenance}</span></div><Button variant="outline" className="mt-5 w-full" onClick={() => toast(`Fiche du bus ${v.id} ouverte`)}>Voir la fiche</Button></article>)}</div> : <DataTable data={vehicles} columns={[{key:"id",label:"Numéro"},{key:"plate",label:"Immatriculation"},{key:"brand",label:"Marque"},{key:"model",label:"Modèle"},{key:"capacity",label:"Capacité"},{key:"year",label:"Année"},{key:"status",label:"Statut",render:statusCell("status")},{key:"circuit",label:"Circuit"},{key:"maintenance",label:"Prochain entretien"}]} />}</AppShell>;
}

export function DriversPage() { return <AppShell title="Chauffeurs"><PageIntro text="Disponibilités, affectations et horaires de l’équipe de transport."><Button onClick={() => toast.success("Nouveau chauffeur prêt à être renseigné")}><Plus />Ajouter un chauffeur</Button></PageIntro><DataTable data={drivers} placeholder="Rechercher un chauffeur…" columns={[{key:"name",label:"Chauffeur"},{key:"phone",label:"Téléphone"},{key:"status",label:"Disponibilité",render:statusCell("status")},{key:"vehicle",label:"Véhicule affecté"},{key:"circuit",label:"Circuit"},{key:"hours",label:"Planning"}]} /></AppShell>; }

export function CircuitsPage() { return <AppShell title="Circuits scolaires"><PageIntro text="Planifiez les zones, capacités et affectations de chaque circuit."><Button variant="outline" onClick={() => toast("Optimisation IA lancée pour la sélection")}>Régénérer avec l’IA</Button><Button onClick={() => toast.success("Nouveau circuit créé")}><Plus />Nouveau circuit</Button></PageIntro><DataTable data={circuits} placeholder="Référence, zone, chauffeur…" columns={[{key:"id",label:"Référence"},{key:"name",label:"Nom"},{key:"zone",label:"Zone"},{key:"students",label:"Élèves"},{key:"vehicle",label:"Véhicule"},{key:"driver",label:"Chauffeur"},{key:"capacity",label:"Capacité"},{key:"time",label:"Horaire"},{key:"status",label:"Statut",render:statusCell("status")}]}/></AppShell>; }

function PageIntro({ text, children }: { text: string; children: React.ReactNode }) { return <div className="mb-5 flex flex-col justify-between gap-4 md:flex-row md:items-center"><p className="text-muted-foreground">{text}</p><div className="flex flex-wrap gap-2">{children}</div></div>; }