import { useMemo, useState } from "react";
import { CalendarClock, CheckCircle2, Eye, FileDown, Filter, MoreHorizontal, Plus, Search, ShieldAlert, Trash2, Wrench } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { StatusBadge } from "@/components/status-badge";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Textarea } from "@/components/ui/textarea";
import { useDemo } from "@/lib/demo-state";
import { driverRoster as drivers, vehicles, type IncidentRecord, type MaintenanceRecord } from "@/lib/mock-data";
import { circuits } from "@/lib/transport-engine";
import { CrisisPanel } from "@/components/crisis-panel";
import { toast } from "sonner";

type Kind = "maintenance" | "incident";
const maintenanceTypes = ["Vidange", "Freinage", "Pneumatiques", "Révision", "Contrôle technique", "Batterie", "Climatisation", "Autre"];
const incidentTypes = ["Panne mécanique", "Crevaison", "Accident mineur", "Retard important", "Véhicule indisponible", "Problème de porte", "Autre"];

export function MaintenancePage() { return <OperationsPage kind="maintenance" />; }
export function IncidentsPage() { return <OperationsPage kind="incident" top={<CrisisPanel />} />; }

function OperationsPage({ kind, top }: { kind: Kind; top?: React.ReactNode }) {
  const demo = useDemo();
  const isMaintenance = kind === "maintenance";
  const data = isMaintenance ? demo.maintenances : demo.incidents;
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("all"); const [level, setLevel] = useState("all");
  const [page, setPage] = useState(1); const [size, setSize] = useState(10); const [selected, setSelected] = useState<string[]>([]);
  const [detail, setDetail] = useState<MaintenanceRecord | IncidentRecord | null>(null);
  const filtered = useMemo(() => data.filter((item) => JSON.stringify(item).toLowerCase().includes(query.toLowerCase()) && (status === "all" || item.status === status) && (level === "all" || (isMaintenance ? (item as MaintenanceRecord).priority : (item as IncidentRecord).severity) === level)), [data, query, status, level, isMaintenance]);
  const shown = filtered.slice((page - 1) * size, page * size); const pages = Math.max(1, Math.ceil(filtered.length / size));
  const closeSelected = () => { selected.forEach((id) => isMaintenance ? demo.updateMaintenance(id, { status: "Terminée" }) : demo.updateIncident(id, { status: "Clos" })); setSelected([]); toast.success(isMaintenance ? "Interventions clôturées" : "Incidents clôturés"); };
  const removeSelected = () => { selected.forEach((id) => isMaintenance ? demo.deleteMaintenance(id) : demo.deleteIncident(id)); setSelected([]); toast.success("Sélection supprimée"); };
  return <AppShell title={isMaintenance ? "Maintenance" : "Incidents"} eyebrow="Pilotage de la flotte">
    {top}
    <div className="mb-6 grid gap-4 md:grid-cols-3"><Summary icon={isMaintenance ? Wrench : ShieldAlert} label={isMaintenance ? "Interventions actives" : "Incidents ouverts"} value={String(data.filter((x) => x.status === (isMaintenance ? "En cours" : "En traitement") || x.status === (isMaintenance ? "Planifiée" : "Nouveau")).length)} /><Summary icon={CalendarClock} label={isMaintenance ? "Prévues ce mois" : "Signalés ce mois"} value={String(data.length)} /><Summary icon={CheckCircle2} label={isMaintenance ? "Terminées" : "Résolus"} value={String(data.filter((x) => x.status === (isMaintenance ? "Terminée" : "Résolu")).length)} /></div>
    <section className="overflow-hidden rounded-lg border bg-card shadow-sm">
      <div className="flex flex-wrap items-center gap-3 border-b p-4"><div className="relative min-w-64 flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={query} onChange={(e)=>{setQuery(e.target.value);setPage(1)}} className="pl-9" placeholder={isMaintenance ? "Référence, véhicule, prestataire…" : "Référence, véhicule, chauffeur…"}/></div><Select value={status} onValueChange={setStatus}><SelectTrigger className="w-44"><Filter/><SelectValue placeholder="Statut"/></SelectTrigger><SelectContent><SelectItem value="all">Tous les statuts</SelectItem>{(isMaintenance?["Planifiée","En cours","Terminée","Reportée"]:["Nouveau","En traitement","Résolu","Clos"]).map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Select value={level} onValueChange={setLevel}><SelectTrigger className="w-40"><SelectValue placeholder={isMaintenance?"Priorité":"Gravité"}/></SelectTrigger><SelectContent><SelectItem value="all">Tous les niveaux</SelectItem>{(isMaintenance?["Faible","Moyenne","Haute","Urgente"]:["Faible","Moyenne","Élevée"]).map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Button variant="outline" onClick={()=>toast.success("Export généré avec succès")}><FileDown/>Exporter</Button><CreateDialog kind={kind}/></div>
      {selected.length>0&&<div className="flex items-center gap-2 border-b bg-secondary/5 px-4 py-3 text-sm"><b>{selected.length} sélectionné(s)</b><Button size="sm" variant="outline" onClick={closeSelected}>Changer le statut</Button><Button size="sm" variant="outline" onClick={()=>toast.success("Export généré avec succès")}>Exporter</Button><Button size="sm" variant="destructive" onClick={removeSelected}><Trash2/>Supprimer</Button></div>}
      <div className="overflow-auto"><table className="w-full min-w-[1120px] text-left text-sm"><thead className="sticky top-0 z-10 bg-table-header text-xs uppercase text-muted-foreground"><tr><th className="px-4 py-3"><Checkbox checked={shown.length>0&&selected.length===shown.length} onCheckedChange={()=>setSelected(selected.length===shown.length?[]:shown.map(x=>x.id))}/></th>{(isMaintenance?["Référence","Véhicule","Type","Date prévue","Intervention","Prestataire","Coût","Statut","Priorité"]:["Référence","Date","Véhicule","Chauffeur","Circuit","Type","Gravité","Description","Statut"]).map(x=><th key={x} className="px-4 py-3">{x}</th>)}<th/></tr></thead><tbody>{shown.map((raw)=><OperationRow key={raw.id} kind={kind} item={raw} selected={selected.includes(raw.id)} toggle={()=>setSelected(s=>s.includes(raw.id)?s.filter(x=>x!==raw.id):[...s,raw.id])} view={()=>setDetail(raw)}/>)}</tbody></table></div>
      <div className="flex flex-wrap items-center justify-between gap-3 border-t px-4 py-3 text-sm text-muted-foreground"><span>{filtered.length} résultats · Page {page} sur {pages}</span><div className="flex items-center gap-2"><Select value={String(size)} onValueChange={(v)=>{setSize(Number(v));setPage(1)}}><SelectTrigger className="w-20"><SelectValue/></SelectTrigger><SelectContent>{[10,25,50].map(x=><SelectItem key={x} value={String(x)}>{x}</SelectItem>)}</SelectContent></Select><Button variant="outline" size="sm" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Précédente</Button><Button variant="outline" size="sm" disabled={page===pages} onClick={()=>setPage(p=>p+1)}>Suivante</Button></div></div>
    </section><DetailSheet kind={kind} item={detail} onClose={()=>setDetail(null)}/>
  </AppShell>;
}

function Summary({icon:Icon,label,value}:{icon:typeof Wrench;label:string;value:string}) { return <article className="rounded-lg border bg-card p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-sm text-muted-foreground">{label}</p><b className="mt-2 block text-3xl">{value}</b></div><span className="grid size-11 place-items-center rounded-md bg-secondary/10 text-secondary"><Icon/></span></div></article>; }
function OperationRow({kind,item,selected,toggle,view}:{kind:Kind;item:MaintenanceRecord|IncidentRecord;selected:boolean;toggle:()=>void;view:()=>void}) { const m=kind==="maintenance"?item as MaintenanceRecord:null; const i=kind==="incident"?item as IncidentRecord:null; return <tr className="border-t transition-colors hover:bg-muted/40"><td className="px-4 py-3"><Checkbox checked={selected} onCheckedChange={toggle}/></td>{m?<><td className="px-4 font-semibold">{m.id}</td><td className="px-4">{m.vehicle}</td><td className="px-4">{m.type}</td><td className="px-4">{m.plannedDate}</td><td className="px-4">{m.interventionDate}</td><td className="px-4">{m.provider}</td><td className="px-4">{m.cost.toLocaleString("fr-FR")} MAD</td><td className="px-4"><StatusBadge>{m.status}</StatusBadge></td><td className="px-4"><StatusBadge>{m.priority}</StatusBadge></td></>:<><td className="px-4 font-semibold">{i?.id}</td><td className="px-4">{i?.date}</td><td className="px-4">{i?.vehicle}</td><td className="px-4">{i?.driver}</td><td className="px-4">{i?.circuit}</td><td className="px-4">{i?.type}</td><td className="px-4"><StatusBadge>{i?.severity}</StatusBadge></td><td className="max-w-56 truncate px-4">{i?.description}</td><td className="px-4"><StatusBadge>{i?.status}</StatusBadge></td></>}<td className="px-4"><DropdownMenu><DropdownMenuTrigger asChild><Button size="icon" variant="ghost" aria-label="Actions"><MoreHorizontal/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={view}><Eye/>Consulter</DropdownMenuItem><DropdownMenuItem onClick={()=>toast.success("Modification enregistrée")}>Modifier</DropdownMenuItem><DropdownMenuItem onClick={()=>toast.success(kind==="maintenance"?"Intervention clôturée":"Incident clôturé")}>Clôturer</DropdownMenuItem><DropdownMenuItem onClick={()=>toast("Échéance reportée")}>Reporter</DropdownMenuItem></DropdownMenuContent></DropdownMenu></td></tr>; }

function CreateDialog({kind}:{kind:Kind}) { const demo=useDemo(); const [open,setOpen]=useState(false); const [vehicle,setVehicle]=useState("B-01"); const [type,setType]=useState(kind==="maintenance"?"Révision":"Panne mécanique"); const [description,setDescription]=useState(""); const create=()=>{ if(kind==="maintenance") demo.addMaintenance({vehicle,type,description:description||"Intervention programmée",plannedDate:"05/10/2026",interventionDate:"—",provider:"Atlas Auto",cost:1200,status:"Planifiée",priority:"Moyenne",notes:"Ajoutée pendant la démonstration."}); else demo.addIncident({vehicle,type,description:description||"Incident déclaré pendant la tournée",date:"29/09/2026 · 14:20",driver:drivers[0]?.name??"Ahmed Benali",circuit:circuits[0]?.id??"C-01",severity:"Moyenne",status:"Nouveau",comment:"Responsable flotte informé."}); setOpen(false);toast.success(kind==="maintenance"?"Maintenance enregistrée":"Incident déclaré");}; return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Plus/>{kind==="maintenance"?"Nouvelle intervention":"Déclarer un incident"}</Button></DialogTrigger><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>{kind==="maintenance"?"Nouvelle intervention":"Déclarer un incident"}</DialogTitle><DialogDescription>Ces informations restent disponibles pendant cette démonstration.</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><Field label="Véhicule"><Select value={vehicle} onValueChange={setVehicle}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{vehicles.map(v=><SelectItem key={v.id} value={v.id}>Bus {v.id} · {v.brand}</SelectItem>)}</SelectContent></Select></Field><Field label="Type"><Select value={type} onValueChange={setType}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{(kind==="maintenance"?maintenanceTypes:incidentTypes).map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></Field><Field label={kind==="maintenance"?"Date prévue":"Date"}><Input type="date" defaultValue="2026-10-05"/></Field><Field label={kind==="maintenance"?"Prestataire":"Circuit / chauffeur"}><Input defaultValue={kind==="maintenance"?"Atlas Auto":"C-01 · Ahmed Benali"}/></Field><div className="sm:col-span-2"><Label>Description</Label><Textarea className="mt-1.5" value={description} onChange={e=>setDescription(e.target.value)} placeholder="Décrivez précisément l’intervention ou l’incident…"/></div><Field label={kind==="maintenance"?"Coût estimé":"Gravité"}><Input defaultValue={kind==="maintenance"?"1200 MAD":"Moyenne"}/></Field><Field label={kind==="maintenance"?"Priorité":"Statut"}><Input defaultValue={kind==="maintenance"?"Moyenne":"Nouveau"}/></Field></div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>Annuler</Button><Button onClick={create}>Enregistrer</Button></DialogFooter></DialogContent></Dialog>; }
function Field({label,children}:{label:string;children:React.ReactNode}) { return <div><Label>{label}</Label><div className="mt-1.5">{children}</div></div>; }
function DetailSheet({kind,item,onClose}:{kind:Kind;item:MaintenanceRecord|IncidentRecord|null;onClose:()=>void}) { if(!item)return null; const m=kind==="maintenance"?item as MaintenanceRecord:null; const i=kind==="incident"?item as IncidentRecord:null; const events=kind==="maintenance"?["Demande créée","Prestataire confirmé","Véhicule préparé","Compte rendu attendu"]:["07:18 — Incident déclaré","07:25 — Responsable flotte informé","07:35 — Bus de remplacement affecté","08:10 — Incident pris en charge"]; return <Sheet open onOpenChange={(v)=>!v&&onClose()}><SheetContent className="w-full overflow-y-auto sm:max-w-xl"><SheetHeader><SheetTitle>{item.id} · {m?.type??i?.type}</SheetTitle><SheetDescription>Bus {m?.vehicle??i?.vehicle} · aperçu détaillé</SheetDescription></SheetHeader><div className="mt-6 space-y-6"><div className="grid grid-cols-2 gap-3">{[["Statut",item.status],[kind==="maintenance"?"Priorité":"Gravité",m?.priority??i?.severity],["Véhicule",m?.vehicle??i?.vehicle],[kind==="maintenance"?"Coût":"Circuit",m?`${m.cost.toLocaleString("fr-FR")} MAD`:i?.circuit]].map(([l,v])=><div key={l} className="rounded-md border p-3"><small className="text-muted-foreground">{l}</small><b className="mt-1 block">{v}</b></div>)}</div><section><h3 className="font-bold">Description</h3><p className="mt-2 text-sm text-muted-foreground">{m?.description??i?.description}</p></section><section><h3 className="font-bold">Pièces jointes</h3><div className="mt-2 rounded-md border border-dashed p-4 text-sm text-muted-foreground">Rapport_intervention.pdf · Photo_vehicule.jpg</div></section><section><h3 className="font-bold">Historique</h3><div className="mt-3 space-y-0">{events.map((x,n)=><div key={x} className="relative border-l-2 border-secondary/30 pb-5 pl-5 text-sm"><span className="absolute -left-1.5 top-1 size-2.5 rounded-full bg-secondary"/><b>{x}</b><p className="mt-1 text-muted-foreground">{n===events.length-1?"Dernière mise à jour":"Action enregistrée dans le suivi"}</p></div>)}</div></section><Button className="w-full" onClick={()=>toast.success("Fiche mise à jour")}>Mettre à jour la fiche</Button></div></SheetContent></Sheet>; }
