import { useState } from "react";
import { CalendarPlus, Filter } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";
import { schedule } from "@/lib/mock-data";
import { toast } from "sonner";

export function PlanningPage() {
  const [view, setView] = useState("week");
  return <AppShell title="Planning"><div className="mb-5 flex flex-col justify-between gap-4 md:flex-row md:items-center"><p className="text-muted-foreground">Planifiez les véhicules, chauffeurs et circuits de la semaine.</p><div className="flex gap-2"><Button variant="outline"><Filter />Filtres</Button><Button onClick={()=>toast.success("Nouvel événement créé")}><CalendarPlus />Créer un événement</Button></div></div><div className="rounded-lg border bg-card shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><ToggleGroup type="single" value={view} onValueChange={v=>v&&setView(v)}><ToggleGroupItem value="day">Jour</ToggleGroupItem><ToggleGroupItem value="week">Semaine</ToggleGroupItem><ToggleGroupItem value="month">Mois</ToggleGroupItem></ToggleGroup><b className="text-sm">28 septembre – 4 octobre 2026</b><div className="flex gap-3 text-xs text-muted-foreground"><span>● Matin</span><span className="text-secondary">● Midi</span><span className="text-primary">● Soir</span></div></div><div className="overflow-x-auto p-4"><div className="grid min-w-[900px] grid-cols-[90px_repeat(5,1fr)] border-l border-t"><div className="bg-table-header p-3" />{["Lundi 28","Mardi 29","Mercredi 30","Jeudi 1","Vendredi 2"].map(d=><div key={d} className="border-b border-r bg-table-header p-3 text-center text-sm font-semibold">{d}</div>)}{["06:00","08:00","10:00","12:00","14:00","16:00"].flatMap((time,row)=>[<div key={time} className="h-24 border-b border-r p-3 text-xs text-muted-foreground">{time}</div>,...[0,1,2,3,4].map(day=><div key={`${row}-${day}`} className="relative h-24 border-b border-r p-1">{(row+day)%3===0 && <button draggable onDragEnd={()=>toast("Événement déplacé")} className={`w-full rounded-md border-l-4 p-2 text-left text-xs shadow-sm ${row===5&&day===1?"border-destructive bg-danger-soft":"border-secondary bg-secondary/10"}`}><b>{schedule[(row+day)%schedule.length].id}</b><span className="block mt-1">{schedule[(row+day)%schedule.length].vehicle} · {schedule[(row+day)%schedule.length].driver.split(" ")[0]}</span>{row===5&&day===1&&<span className="mt-1 block font-bold text-destructive">Conflit détecté</span>}</button>}</div>)])}</div></div></div></AppShell>;
}