/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentIaRouteImport } from './routes/agent-ia'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ChauffeursRouteImport } from './routes/chauffeurs'
import { Route as CircuitsRouteImport } from './routes/circuits'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ElevesRouteImport } from './routes/eleves'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as VehiculesRouteImport } from './routes/vehicules'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIaRoute = AgentIaRouteImport.update({
  id: '/agent-ia',
  path: '/agent-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ChauffeursRoute = ChauffeursRouteImport.update({
  id: '/chauffeurs',
  path: '/chauffeurs',
  getParentRoute: () => rootRouteImport,
} as any)
const CircuitsRoute = CircuitsRouteImport.update({
  id: '/circuits',
  path: '/circuits',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ElevesRoute = ElevesRouteImport.update({
  id: '/eleves',
  path: '/eleves',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiculesRoute = VehiculesRouteImport.update({
  id: '/vehicules',
  path: '/vehicules',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-ia': typeof AgentIaRoute
  '/analytics': typeof AnalyticsRoute
  '/chauffeurs': typeof ChauffeursRoute
  '/circuits': typeof CircuitsRoute
  '/dashboard': typeof DashboardRoute
  '/eleves': typeof ElevesRoute
  '/incidents': typeof IncidentsRoute
  '/maintenance': typeof MaintenanceRoute
  '/parametres': typeof ParametresRoute
  '/planning': typeof PlanningRoute
  '/vehicules': typeof VehiculesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-ia': typeof AgentIaRoute
  '/analytics': typeof AnalyticsRoute
  '/chauffeurs': typeof ChauffeursRoute
  '/circuits': typeof CircuitsRoute
  '/dashboard': typeof DashboardRoute
  '/eleves': typeof ElevesRoute
  '/incidents': typeof IncidentsRoute
  '/maintenance': typeof MaintenanceRoute
  '/parametres': typeof ParametresRoute
  '/planning': typeof PlanningRoute
  '/vehicules': typeof VehiculesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-ia': typeof AgentIaRoute
  '/analytics': typeof AnalyticsRoute
  '/chauffeurs': typeof ChauffeursRoute
  '/circuits': typeof CircuitsRoute
  '/dashboard': typeof DashboardRoute
  '/eleves': typeof ElevesRoute
  '/incidents': typeof IncidentsRoute
  '/maintenance': typeof MaintenanceRoute
  '/parametres': typeof ParametresRoute
  '/planning': typeof PlanningRoute
  '/vehicules': typeof VehiculesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-ia'
    | '/analytics'
    | '/chauffeurs'
    | '/circuits'
    | '/dashboard'
    | '/eleves'
    | '/incidents'
    | '/maintenance'
    | '/parametres'
    | '/planning'
    | '/vehicules'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-ia'
    | '/analytics'
    | '/chauffeurs'
    | '/circuits'
    | '/dashboard'
    | '/eleves'
    | '/incidents'
    | '/maintenance'
    | '/parametres'
    | '/planning'
    | '/vehicules'
  id:
    | '__root__'
    | '/'
    | '/agent-ia'
    | '/analytics'
    | '/chauffeurs'
    | '/circuits'
    | '/dashboard'
    | '/eleves'
    | '/incidents'
    | '/maintenance'
    | '/parametres'
    | '/planning'
    | '/vehicules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentIaRoute: typeof AgentIaRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ChauffeursRoute: typeof ChauffeursRoute
  CircuitsRoute: typeof CircuitsRoute
  DashboardRoute: typeof DashboardRoute
  ElevesRoute: typeof ElevesRoute
  IncidentsRoute: typeof IncidentsRoute
  MaintenanceRoute: typeof MaintenanceRoute
  ParametresRoute: typeof ParametresRoute
  PlanningRoute: typeof PlanningRoute
  VehiculesRoute: typeof VehiculesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-ia': {
      id: '/agent-ia'
      path: '/agent-ia'
      fullPath: '/agent-ia'
      preLoaderRoute: typeof AgentIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chauffeurs': {
      id: '/chauffeurs'
      path: '/chauffeurs'
      fullPath: '/chauffeurs'
      preLoaderRoute: typeof ChauffeursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circuits': {
      id: '/circuits'
      path: '/circuits'
      fullPath: '/circuits'
      preLoaderRoute: typeof CircuitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eleves': {
      id: '/eleves'
      path: '/eleves'
      fullPath: '/eleves'
      preLoaderRoute: typeof ElevesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicules': {
      id: '/vehicules'
      path: '/vehicules'
      fullPath: '/vehicules'
      preLoaderRoute: typeof VehiculesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentIaRoute: AgentIaRoute,
  AnalyticsRoute: AnalyticsRoute,
  ChauffeursRoute: ChauffeursRoute,
  CircuitsRoute: CircuitsRoute,
  DashboardRoute: DashboardRoute,
  ElevesRoute: ElevesRoute,
  IncidentsRoute: IncidentsRoute,
  MaintenanceRoute: MaintenanceRoute,
  ParametresRoute: ParametresRoute,
  PlanningRoute: PlanningRoute,
  VehiculesRoute: VehiculesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
